# Generated by Django 3.1.3 on 2021-10-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211012_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
