# Generated by Django 3.1.3 on 2021-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='courier',
            name='fcn_tokens',
            field=models.TextField(blank=True),
        ),
    ]
