# Generated by Django 3.1.3 on 2021-10-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211026_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='fcn_tokens',
            new_name='fcm_tokens',
        ),
    ]
