# Generated by Django 3.1.3 on 2021-10-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211026_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='fcm_tokens',
            new_name='fcm_token',
        ),
    ]
