"""
Django settings for fastparcel project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os 
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ud4@ot-zoc6n@xdx2m8f5wyj&u5)wmm)-r_%qp4#tvz1=)&&&y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'bootstrap4',
    'social_django',
    'core.apps.CoreConfig',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ProfileMiddleware'
]

ROOT_URLCONF = 'fastparcel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fastparcel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'


LOGIN_URL = '/sign-in/'
LOGIN_REDIRECT_URL = '/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'



AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_FACEBOOK_KEY = "328165245742053"
SOCIAL_AUTH_FACEBOOK_SECRET = "60aae29ea16d2fc6a8eb72bf3ccac0e6"
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email'
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'pedram1990shah@gmail.com'
EMAIL_HOST_PASSWORD = 'Shahin9090'
DEFAULT_FROM_EMAIL = 'Bizlution <no-reply@bizlution.localhost'

FIREBASE_ADMIN_CREDENTIAL = os.path.join(BASE_DIR, 'bizlutionp-firebase-adminsdk-3zlf5-49400c70cb.json')

STRIPE_API_PUBLIC_KEY = "pk_test_51JhvZDIlnLB5lfru98PHeY0VpHEo0NSea120RDFGc4NgyaMMy2K8cWFYdfWfPkCWn6WUnDDGzsQuO3q8fh1ODYd800vWViziee"
STRIPE_API_SECRET_KEY = "sk_test_51JhvZDIlnLB5lfru5OVjUcpKS5FaqQBAPMtxQlCnEhXBEv29OleHxB1XVr0LcSdsIQURcx5DMePQsqXXXJYasE9200PNo87QED"


GOOGLE_MAP_API_KEY = "AIzaSyDVaBNtguXgQcqcAg32XoTGDxyx8fcn7tA"

PAYPAL_MODE = "sandbox"
PAYPAL_CLIENT_ID = "AdxIABTjF_I6V6LQu67gDejRZEpvp8bbcFbN8wL-CXB66-qNlIYTxitCP6K36gLZsZ20ippmR9_0Sxnw"
PAYPAL_CLIENT_SECRET = "EECjB3z-i5LKmVbcqqP7NUq118T94rfgX2AfpDCodsM61NrKaq_ASEgWIMibwsqKJFUPI0UI6tNcCGtu"


NOTIFICATION_URL = "https://7fc1-31-208-78-236.ngrok.io"


ASGI_APPLICATION = "fastparcel.asgi.application"


# Channels
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": ['127.0.0.1','6739'],
#         },
#     },
# }
